version: '3.8'

services:
  postgres:
    container_name: rpg-postgres
    image: postgres:14
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: postgres
    ports:
      - "5435:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped

  api:
    container_name: rpg-api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3003:3000"
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USERNAME: postgres
      DB_PASSWORD: 12345
      DB_NAME: postgres
    depends_on:
      - postgres
    command: pnpm dev
    restart: unless-stopped

volumes:
  pgdata:
